// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.27;

error DEPOSIT__INVALID_AMOUNT();
error WITHDRAW__INVALID_AMOUNT();
error WITHDRAW__INVALID_BALANCE();
error INCREASE_BALANCE__INVALID_AMOUNT();
error DECREASE_BALANCE__INVALID_AMOUNT();
error DECREASE_BALANCE__INSUFFICIENT_BALANCE();
error INVALID_ADDRESS();
error TWAB__INVALID_PERIOD_OFFSET();
error TWAB_BETWEEN__INVALID_TIME_RANGE();
error TWAB_BETWEEN__ISUFFICIENT_HISTORY();
